upkeep(kafka-cost): Make GCP auth error explicit
Instead of just:
```
2025-08-05T09:20:55.806155Z  INFO kafka_cost: started kafka-cost
Error: http error: error decoding response body

Caused by:
   0: error decoding response body
   1: missing field `access_token` at line 6 column 1

Location:
    src/main.rs:106:23
```